jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

auth:
  security:
    remember-me:
      key: 5c37379956bd1242f5636c8cb322c2966ad81277